@host= http://localhost:8001/api/auth

@email = test@test.com
@code = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJpZCI6MSwiaWF0IjoxNjg3MjEzNDIyLCJleHAiOjE2ODcyMTcwMjJ9.BWg7yIYLo7dYYNAGNRBa8PmagJ_0QX3-pVT0ya6M0MQ

### Generate and send conde
GET {{host}}/code
Content-Type: application/json

{
    "email" : "{{email}}"
}

### Login
POST {{host}}/login
Content-Type: application/json

{
    "email" : "{{email}}",
    "code" : "{{code}}"
}