@host= http://localhost:8001/api/auth

@email = test@test.com
@code = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJpZCI6MSwiaWF0IjoxNjg3Mjg2Mzk0LCJleHAiOjE2ODcyODk5OTR9.FuUJe4gJe_SuYW9irsdzPJpz7ElwOCkpZlXf7YkN0EA

### Generate and send conde
GET {{host}}/code
Content-Type: application/json

{
    "email" : "{{email}}"
}

### Login
POST {{host}}/login
Content-Type: application/json

{
    "email" : "{{email}}",
    "code" : "{{code}}"
}