@auth= {{api}}/auth

@email = test@test.com

### Generate and send conde
# @name getCode
POST {{auth}}/code
Content-Type: application/json

{
    "email" : "{{email}}"
}

### Login
# @name login
POST {{auth}}/login
Content-Type: application/json

{
    "email" : "{{email}}",
    "code" : "{{{{getCode.response.body.$.code}}}}"
}


