@category= {{api}}/category

### Get all categories
# @name getAll
GET {{category}}/
Authorization: {{token}}

### Get category by id
# @name getById
GET {{category}}/1
Authorization: {{token}}

### Create category
# @name store
POST {{category}}/store
Authorization: {{token}}
Content-Type: application/json

{
    "name": "Name",
    "description": "Description of new category"
}

### Update category
# @name update
PUT {{category}}/{{store.response.body.$.product.id}}
Authorization: {{token}}
Content-Type: application/json

{
    "name": "Name (EDITED)"
}

### Delete category
# @name delete
DELETE  {{category}}/{{store.response.body.$.product.id}}
Authorization: {{token}}