@host= http://localhost:8001/api/person
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZV9pZCI6MSwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwiZnVsbE5hbWUiOiJWZXJhIFdpbGxtcyIsImlhdCI6MTY4OTgwMzQwNywiZXhwIjoxNjg5OTQ3NDA3fQ.Nsb7rwqTWGeveihVGDv6hBoZqHJmM9MoKf8xEJtZpCQ

### Get all people
GET {{host}}/
Authorization: {{token}}

### Get person by id
GET {{host}}/1
Authorization: {{token}}

### Create person
POST {{host}}/store
Authorization: {{token}}
Content-Type: application/json

{
    "type_person": "Legal",
    "document_type": "CUIT",
    "document_number": "document_number of new person",

    "name": "Name person",
    "address": "address of new person",
    "phone": "phone of new person"

}

### Update person
PUT {{host}}/11
Authorization: {{token}}
Content-Type: application/json

{
    "name": "Name person (EDITED)"
}

### Delete person
DELETE  {{host}}/11
Authorization: {{token}}