@person= {{api}}/person

### Get all people
# @name getAll
GET {{person}}/
Authorization: {{token}}

### Get all providers
# @name getAllProviders
GET {{person}}/providers
Authorization: {{token}}

### Get all clients
# @name getAllClients
GET {{person}}/clients
Authorization: {{token}}

### Get person by id
# @name getById
GET {{person}}/1
Authorization: {{token}}

### Create person
# @name store
POST {{person}}/store
Authorization: {{token}}
Content-Type: application/json

{
    "type_person": "Legal",
    "document_type": "CUIT",
    "document_number": "4864685484",

    "name": "Name person",
    "address": "address of new person",
    "phone": "phone of new person"

}

### Update person
# @name update
PUT {{person}}/{{store.response.body.$.person.id}}
Authorization: {{token}}
Content-Type: application/json

{
    "name": "Name person (EDITED)"
}

### Delete person
# @name delete
DELETE  {{person}}/{{store.response.body.$.person.id}}
Authorization: {{token}}