@product= {{api}}/product

### Get all products
# @name getAll
GET {{product}}/
Authorization: {{token}}

### Get product by id
# @name getById
GET {{product}}/1
Authorization: {{token}}

### Get product by category id
# @name getByCategory
GET {{product}}/category/1
Authorization: {{token}}

### Search product by field
# @name searchByField
POSt {{product}}/search
Authorization: {{token}}
Content-Type: application/json

{
    "code" : "44"
}

### Create product
# @name store
POST {{product}}/store
Authorization: {{token}}
Content-Type: application/json

{
	"category_id": "1",

	"name": "El Nombre",
	"type": "producto",
	"description": "Esta es la descripcion del nuevo producto",
	"code": "das4f61",
	"img": "https://dummyimage.com/300x200/000/fff.png",

	"price": "30",
	"stock": "0"
}

### Update product
# @name update
PUT {{product}}/{{store.response.body.$.product.id}}
Authorization: {{token}}
Content-Type: application/json

{
    "name": "El Nombre (EDITED)"
}

### Delete product
# @name delete
DELETE  {{product}}/{{store.response.body.$.product.id}}
Authorization: {{token}}