@sale= {{api}}/sale

### Get all sales
# @name getAll
GET {{sale}}/
Authorization: {{token}}

### Get sale by id
# @name getById
GET {{sale}}/1
Authorization: {{token}}

### Create sale
# @name store
POST {{sale}}/store
Authorization: {{token}}
Content-Type: application/json

{
    "user_id": 1,
	"client_id": 1,

	"voucher_series": "Serie C-01",
	"voucher_type": "FACTURA A",

	"products":[
		{
			"id": 1,
			"price":50,
			"stock": 5
		},
		{
			"id": 2,
			"price": 50,
			"stock": 5
		}
	]
}

### Update sale
# @name update
PUT {{sale}}/{{store.response.body.$.sale.id}}
Authorization: {{token}}
Content-Type: application/json

{
    "voucher_type": "FACTURA B"
}

### Delete sale
# @name delete
DELETE  {{sale}}/{{store.response.body.$.sale.id}}
Authorization: {{token}}